{{- if and .Values.omni.serviceAccountKey.value (not .Values.omni.serviceAccountKey.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omni-exporter.fullname" . }}
  labels:
    {{- include "omni-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  OMNI_SERVICE_ACCOUNT_KEY: {{ .Values.omni.serviceAccountKey.value | quote }}
{{- end }}
